version: '3.5'
services:

  broker:
    image: rabbitmq:3
    env_file: &envfile
      - .env
    ports:
      - 5672:5672

  web:
    build: .
    image: &celery sursur/vaccine-slot-tracker
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file: *envfile
    depends_on:
      - broker
    restart: on-failure

  celery-worker:
    image: *celery
    container_name: celery-worker
    command: celery -A tracker worker --loglevel=info
    env_file: *envfile
    volumes:
      - .:/app
    depends_on:
      - broker
      - web

  celery-beat:
    image: *celery
    container_name: celery-beat
    command: celery -A tracker beat --loglevel=info
    env_file: *envfile
    volumes:
      - .:/app
    depends_on:
      - broker
      - web
