# Generated by Django 3.2 on 2021-05-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='district_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
